version: "3.9"
   
services:
   db:
    image: mysql:8.0.26
    restart: always
    environment:
      - MYSQL_DATABASE=mysitedb
      - MYSQL_USER=chitrang
      - MYSQL_PASSWORD=Test@123
      - MYSQL_ROOT_PASSWORD=Canada@2017
    ports:
      - "3307:3306"      
    volumes:
      - ./dbdata:/var/lib/mysql  
   web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db